=encoding utf8

=head1 todo

perli C<use Ethics;>  is pythonic C<import this;>

C<use Perliament;> is...

=head3 Ethics

B<print this to console:>

	#!/bin/perl
	#`[ℝeal Perl Programmers] use Ethics;
	=begin comment
		ℝeal Perl Programmers use Perl.
		ℝeal Perl Programmers prefer things to be visually distinct. (Larry Wall @ 1997)
		ℝeal Perl Programmers don't use indices. (https://en.wikipedia.org/wiki/Learning_Perl)
		ℝeal Perl Programmers...
	=end comment

I<demonstrates all syntax of L<docommentation|https://docs.perl6.org/language/syntax#Comments>>

=head1 the art of computer programming

piet is steganographic meta art

prolog is photographic raster art

haskell is scalable vector art

assembly is spriteful pixel art

L<java|http://www.webmd.com/diet/news/20061011/decaf-coffee-isnt-caffeine-free> is L<decaffeinated|http://www.sbs.com.au
/food/article/2017/02/27/chemicals-and-caffeine-whats-deal-decaf> latte art

python_is_crayonic_fingerpainting_art

perl is textual ascii art
